"""\
Based on types in uchar.h from ICU

Created on May 2, 2020

@author Eric Mader
"""

U_JT_NON_JOINING = 0  # [U]
U_JT_JOIN_CAUSING = 1  # [C]
U_JT_DUAL_JOINING = 2  # [D]
U_JT_LEFT_JOINING = 3  # [L]
U_JT_RIGHT_JOINING = 4  # [R]
U_JT_TRANSPARENT = 5  # [T]

joiningTypes = {
    U_JT_NON_JOINING: 'U',
    U_JT_JOIN_CAUSING: 'C',
    U_JT_DUAL_JOINING: 'D',
    U_JT_LEFT_JOINING: 'L',
    U_JT_RIGHT_JOINING: 'R',
    U_JT_TRANSPARENT: 'T'
}

U_JG_NO_JOINING_GROUP = 0
U_JG_AIN = 1
U_JG_ALAPH = 2
U_JG_ALEF = 3
U_JG_BEH = 4
U_JG_BETH = 5
U_JG_DAL = 6
U_JG_DALATH_RISH = 7
U_JG_E = 8
U_JG_FEH = 9
U_JG_FINAL_SEMKATH = 10
U_JG_GAF = 11
U_JG_GAMAL = 12
U_JG_HAH = 13
U_JG_TEH_MARBUTA_GOAL = 14
U_JG_HAMZA_ON_HEH_GOAL = U_JG_TEH_MARBUTA_GOAL
U_JG_HE = 15
U_JG_HEH = 16
U_JG_HEH_GOAL = 17
U_JG_HETH = 18
U_JG_KAF = 19
U_JG_KAPH = 20
U_JG_KNOTTED_HEH = 21
U_JG_LAM = 22
U_JG_LAMADH = 23
U_JG_MEEM = 24
U_JG_MIM = 25
U_JG_NOON = 26
U_JG_NUN = 27
U_JG_PE = 28
U_JG_QAF = 29
U_JG_QAPH = 30
U_JG_REH = 31
U_JG_REVERSED_PE = 32
U_JG_SAD = 33
U_JG_SADHE = 34
U_JG_SEEN = 35
U_JG_SEMKATH = 36
U_JG_SHIN = 37
U_JG_SWASH_KAF = 38
U_JG_SYRIAC_WAW = 39
U_JG_TAH = 40
U_JG_TAW = 41
U_JG_TEH_MARBUTA = 42
U_JG_TETH = 43
U_JG_WAW = 44
U_JG_YEH = 45
U_JG_YEH_BARREE = 46
U_JG_YEH_WITH_TAIL = 47
U_JG_YUDH = 48
U_JG_YUDH_HE = 49
U_JG_ZAIN = 50
U_JG_FE = 51
U_JG_KHAPH = 52
U_JG_ZHAIN = 53
U_JG_BURUSHASKI_YEH_BARREE = 54
U_JG_FARSI_YEH = 55
U_JG_NYA = 56
U_JG_ROHINGYA_YEH = 57
U_JG_MANICHAEAN_ALEPH = 58
U_JG_MANICHAEAN_AYIN = 59
U_JG_MANICHAEAN_BETH = 60
U_JG_MANICHAEAN_DALETH = 61
U_JG_MANICHAEAN_DHAMEDH = 62
U_JG_MANICHAEAN_FIVE = 63
U_JG_MANICHAEAN_GIMEL = 64
U_JG_MANICHAEAN_HETH = 65
U_JG_MANICHAEAN_HUNDRED = 66
U_JG_MANICHAEAN_KAPH = 67
U_JG_MANICHAEAN_LAMEDH = 68
U_JG_MANICHAEAN_MEM = 69
U_JG_MANICHAEAN_NUN = 70
U_JG_MANICHAEAN_ONE = 71
U_JG_MANICHAEAN_PE = 72
U_JG_MANICHAEAN_QOPH = 73
U_JG_MANICHAEAN_RESH = 74
U_JG_MANICHAEAN_SADHE = 75
U_JG_MANICHAEAN_SAMEKH = 76
U_JG_MANICHAEAN_TAW = 77
U_JG_MANICHAEAN_TEN = 78
U_JG_MANICHAEAN_TETH = 79
U_JG_MANICHAEAN_THAMEDH = 80
U_JG_MANICHAEAN_TWENTY = 81
U_JG_MANICHAEAN_WAW = 82
U_JG_MANICHAEAN_YODH = 83
U_JG_MANICHAEAN_ZAYIN = 84
U_JG_STRAIGHT_WAW = 85
U_JG_AFRICAN_FEH = 86
U_JG_AFRICAN_NOON = 87
U_JG_AFRICAN_QAF = 88
U_JG_MALAYALAM_BHA = 89
U_JG_MALAYALAM_JA = 90
U_JG_MALAYALAM_LLA = 91
U_JG_MALAYALAM_LLLA = 92
U_JG_MALAYALAM_NGA = 93
U_JG_MALAYALAM_NNA = 94
U_JG_MALAYALAM_NNNA = 95
U_JG_MALAYALAM_NYA = 96
U_JG_MALAYALAM_RA = 97
U_JG_MALAYALAM_SSA = 98
U_JG_MALAYALAM_TTA = 99
U_JG_HANIFI_ROHINGYA_KINNA_YA = 100
U_JG_HANIFI_ROHINGYA_PA = 101

joiningGroups = {
    U_JG_NO_JOINING_GROUP: "JG_NO_JOINING_GROUP",
    U_JG_AIN: "JG_AIN",
    U_JG_ALAPH: "JG_ALAPH",
    U_JG_ALEF: "JG_ALEF",
    U_JG_BEH: "JG_BEH",
    U_JG_BETH: "JG_BETH",
    U_JG_DAL: "JG_DAL",
    U_JG_DALATH_RISH: "JG_DALATH_RISH",
    U_JG_E: "JG_E",
    U_JG_FEH: "JG_FEH",
    U_JG_FINAL_SEMKATH: "JG_FINAL_SEMKATH",
    U_JG_GAF: "JG_GAF",
    U_JG_GAMAL: "JG_GAMAL",
    U_JG_HAH: "JG_HAH",
    U_JG_TEH_MARBUTA_GOAL: "JG_TEH_MARBUTA_GOAL",
    #U_JG_HAMZA_ON_HEH_GOAL: "JG_U_JG_HAMZA_ON_HEH_GOAL"
    U_JG_HE: "JG_HE",
    U_JG_HEH: "JG_HEH",
    U_JG_HEH_GOAL: "JG_HEH_GOAL",
    U_JG_HETH: "JG_HETH",
    U_JG_KAF: "JG_KAF",
    U_JG_KAPH: "JG_KAPH",
    U_JG_KNOTTED_HEH: "JG_KNOTTED_HEH",
    U_JG_LAM: "JG_LAM",
    U_JG_LAMADH: "JG_LAMADH",
    U_JG_MEEM: "JG_MEEM",
    U_JG_MIM: "JG_MIM",
    U_JG_NOON: "JG_NOON",
    U_JG_NUN: "JG_NUN",
    U_JG_PE: "JG_PE",
    U_JG_QAF: "JG_QAF",
    U_JG_QAPH: "JG_QAPH",
    U_JG_REH: "JG_REH",
    U_JG_REVERSED_PE: "JG_REVERSED_PE",
    U_JG_SAD: "JG_SAD",
    U_JG_SADHE: "JG_SADHE",
    U_JG_SEEN: "JG_SEEN",
    U_JG_SEMKATH: "JG_SEMKATH",
    U_JG_SHIN: "JG_SHIN",
    U_JG_SWASH_KAF: "JG_SWASH_KAF",
    U_JG_SYRIAC_WAW: "JG_SYRIAC_WAW",
    U_JG_TAH: "JG_TAH",
    U_JG_TAW: "JG_TAW",
    U_JG_TEH_MARBUTA: "JG_TEH_MARBUTA",
    U_JG_TETH: "JG_TETH",
    U_JG_WAW: "JG_WAW",
    U_JG_YEH: "JG_YEH",
    U_JG_YEH_BARREE: "JG_YEH_BARREE",
    U_JG_YEH_WITH_TAIL: "JG_YEH_WITH_TAIL",
    U_JG_YUDH: "JG_YUDH",
    U_JG_YUDH_HE: "JG_YUDH_HE",
    U_JG_ZAIN: "JG_ZAIN",
    U_JG_FE: "JG_FE",
    U_JG_KHAPH: "JG_KHAPH",
    U_JG_ZHAIN: "JG_ZHAIN",
    U_JG_BURUSHASKI_YEH_BARREE: "JG_BURUSHASKI_YEH_BARREE",
    U_JG_FARSI_YEH: "JG_FARSI_YEH",
    U_JG_NYA: "JG_NYA",
    U_JG_ROHINGYA_YEH: "JG_ROHINGYA_YEH",
    U_JG_MANICHAEAN_ALEPH: "JG_MANICHAEAN_ALEPH",
    U_JG_MANICHAEAN_AYIN: "JG_MANICHAEAN_AYIN",
    U_JG_MANICHAEAN_BETH: "JG_MANICHAEAN_BETH",
    U_JG_MANICHAEAN_DALETH: "JG_MANICHAEAN_DALETH",
    U_JG_MANICHAEAN_DHAMEDH: "JG_MANICHAEAN_DHAMEDH",
    U_JG_MANICHAEAN_FIVE: "JG_MANICHAEAN_FIVE",
    U_JG_MANICHAEAN_GIMEL: "JG_MANICHAEAN_GIMEL",
    U_JG_MANICHAEAN_HETH: "JG_MANICHAEAN_HETH",
    U_JG_MANICHAEAN_HUNDRED: "JG_MANICHAEAN_HUNDRED",
    U_JG_MANICHAEAN_KAPH: "JG_MANICHAEAN_KAPH",
    U_JG_MANICHAEAN_LAMEDH: "JG_MANICHAEAN_LAMEDH",
    U_JG_MANICHAEAN_MEM: "JG_MANICHAEAN_MEM",
    U_JG_MANICHAEAN_NUN: "JG_MANICHAEAN_NUN",
    U_JG_MANICHAEAN_ONE: "JG_MANICHAEAN_ONE",
    U_JG_MANICHAEAN_PE: "JG_MANICHAEAN_PE",
    U_JG_MANICHAEAN_QOPH: "JG_MANICHAEAN_QOPH",
    U_JG_MANICHAEAN_RESH: "JG_MANICHAEAN_RESH",
    U_JG_MANICHAEAN_SADHE: "JG_MANICHAEAN_SADHE",
    U_JG_MANICHAEAN_SAMEKH: "JG_MANICHAEAN_SAMEKH",
    U_JG_MANICHAEAN_TAW: "JG_MANICHAEAN_TAW",
    U_JG_MANICHAEAN_TEN: "JG_MANICHAEAN_TEN",
    U_JG_MANICHAEAN_TETH: "JG_MANICHAEAN_TETH",
    U_JG_MANICHAEAN_THAMEDH: "JG_MANICHAEAN_THAMEDH",
    U_JG_MANICHAEAN_TWENTY: "JG_MANICHAEAN_TWENTY",
    U_JG_MANICHAEAN_WAW: "JG_MANICHAEAN_WAW",
    U_JG_MANICHAEAN_YODH: "JG_MANICHAEAN_YODH",
    U_JG_MANICHAEAN_ZAYIN: "JG_MANICHAEAN_ZAYIN",
    U_JG_STRAIGHT_WAW: "JG_STRAIGHT_WAW",
    U_JG_AFRICAN_FEH: "JG_AFRICAN_FEH",
    U_JG_AFRICAN_NOON: "JG_AFRICAN_NOON",
    U_JG_AFRICAN_QAF: "JG_AFRICAN_QAF",
    U_JG_MALAYALAM_BHA: "JG_MALAYALAM_BHA",
    U_JG_MALAYALAM_JA: "JG_MALAYALAM_JA",
    U_JG_MALAYALAM_LLA: "JG_MALAYALAM_LLA",
    U_JG_MALAYALAM_LLLA: "JG_MALAYALAM_LLLA",
    U_JG_MALAYALAM_NGA: "JG_MALAYALAM_NGA",
    U_JG_MALAYALAM_NNA: "JG_MALAYALAM_NNA",
    U_JG_MALAYALAM_NNNA: "JG_MALAYALAM_NNNA",
    U_JG_MALAYALAM_NYA: "JG_MALAYALAM_NYA",
    U_JG_MALAYALAM_RA: "JG_MALAYALAM_RA",
    U_JG_MALAYALAM_SSA: "JG_MALAYALAM_SSA",
    U_JG_MALAYALAM_TTA: "JG_MALAYALAM_TTA",
    U_JG_HANIFI_ROHINGYA_KINNA_YA: "JG_HANIFI_ROHINGYA_KINNA_YA",
    U_JG_HANIFI_ROHINGYA_PA: "JG_HANIFI_ROHINGYA_PA",
}