"""\
Test for UnicodeData.CharNames

Created on July 31, 2021

@author Eric Mader
"""

import pytest
from UnicodeData.CharNames import CharNames, U_UNICODE_CHAR_NAME, U_EXTENDED_CHAR_NAME, U_CHAR_NAME_ALIAS

charNames = [
    (chr(0x00AF), "MACRON", U_UNICODE_CHAR_NAME),
    ('K', "LATIN CAPITAL LETTER K", U_UNICODE_CHAR_NAME),
    ('k', "LATIN SMALL LETTER K", U_UNICODE_CHAR_NAME),
    (chr(0x0901), "DEVANAGARI SIGN CANDRABINDU", U_UNICODE_CHAR_NAME),
    ("क", "DEVANAGARI LETTER KA", U_UNICODE_CHAR_NAME),
    ("㏠", "IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY ONE", U_UNICODE_CHAR_NAME),
    ("㏰", "IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY SEVENTEEN", U_UNICODE_CHAR_NAME),
    ("漢", "CJK UNIFIED IDEOGRAPH-6F22", U_UNICODE_CHAR_NAME),
    ("한", "HANGUL SYLLABLE HAN", U_UNICODE_CHAR_NAME),
    ("궄", "HANGUL SYLLABLE GUK", U_UNICODE_CHAR_NAME),
    ("어", "HANGUL SYLLABLE EO", U_UNICODE_CHAR_NAME),
    ("쪍", "HANGUL SYLLABLE JJYEOLG", U_UNICODE_CHAR_NAME),
    (chr(0x17020), "TANGUT IDEOGRAPH-17020", U_UNICODE_CHAR_NAME),

    ("Ƣ", "LATIN CAPITAL LETTER OI", U_UNICODE_CHAR_NAME),
    ("ƣ", "LATIN SMALL LETTER OI", U_UNICODE_CHAR_NAME),
    ("[", "<start punctuation-005B>", U_EXTENDED_CHAR_NAME),
    # ("]", "<end punctuation-005D>", U_EXTENDED_CHAR_NAME),
    ("¯", "<modifier symbol-00AF>", U_EXTENDED_CHAR_NAME),
    ("K", "<uppercase letter-004B>", U_EXTENDED_CHAR_NAME),
    ("k", "<lowercase letter-006B>", U_EXTENDED_CHAR_NAME),

    (chr(0x01A2), "LATIN CAPITAL LETTER GHA", U_CHAR_NAME_ALIAS),
    (chr(0x01A3), "LATIN SMALL LETTER GHA", U_CHAR_NAME_ALIAS),
    (chr(0x0709), "SYRIAC SUBLINEAR COLON SKEWED LEFT", U_CHAR_NAME_ALIAS),
    (chr(0x0CDE), "KANNADA LETTER LLLA", U_CHAR_NAME_ALIAS),
    (chr(0x0E9D), "LAO LETTER FO FON", U_CHAR_NAME_ALIAS),
    (chr(0x0E9F), "LAO LETTER FO FAY", U_CHAR_NAME_ALIAS),
    (chr(0x0EA3), "LAO LETTER RO", U_CHAR_NAME_ALIAS),
    (chr(0x0EA5), "LAO LETTER LO", U_CHAR_NAME_ALIAS),
    (chr(0x0FD0), "TIBETAN MARK BKA- SHOG GI MGO RGYAN", U_CHAR_NAME_ALIAS),
    (chr(0x11EC), "HANGUL JONGSEONG YESIEUNG-KIYEOK", U_CHAR_NAME_ALIAS),
    (chr(0x11ED), "HANGUL JONGSEONG YESIEUNG-SSANGKIYEOK", U_CHAR_NAME_ALIAS),
    (chr(0x11EE), "HANGUL JONGSEONG SSANGYESIEUNG", U_CHAR_NAME_ALIAS),
    (chr(0x11EF), "HANGUL JONGSEONG YESIEUNG-KHIEUKH", U_CHAR_NAME_ALIAS),
    (chr(0x2118), "WEIERSTRASS ELLIPTIC FUNCTION", U_CHAR_NAME_ALIAS),
    (chr(0x2448), "MICR ON US SYMBOL", U_CHAR_NAME_ALIAS),
    (chr(0x2449), "MICR DASH SYMBOL", U_CHAR_NAME_ALIAS),
    (chr(0x2B7A), "LEFTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE VERTICAL STROKE", U_CHAR_NAME_ALIAS),
    (chr(0x2B7C), "RIGHTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE VERTICAL STROKE", U_CHAR_NAME_ALIAS),
    (chr(0xA015), "YI SYLLABLE ITERATION MARK", U_CHAR_NAME_ALIAS),
    (chr(0xFE18), "PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRACKET", U_CHAR_NAME_ALIAS),
    (chr(0x122D4), "CUNEIFORM SIGN NU11 TENU", U_CHAR_NAME_ALIAS),
    (chr(0x122D5), "CUNEIFORM SIGN NU11 OVER NU11 BUR OVER BUR", U_CHAR_NAME_ALIAS),
    (chr(0x16E56), "MEDEFAIDRIN CAPITAL LETTER H", U_CHAR_NAME_ALIAS),
    (chr(0x16E57), "MEDEFAIDRIN CAPITAL LETTER NG", U_CHAR_NAME_ALIAS),
    (chr(0x16E76), "MEDEFAIDRIN SMALL LETTER H", U_CHAR_NAME_ALIAS),
    (chr(0x16E77), "MEDEFAIDRIN SMALL LETTER NG", U_CHAR_NAME_ALIAS),
    (chr(0x1B001), "HENTAIGANA LETTER E-1", U_CHAR_NAME_ALIAS),
    (chr(0x1D0C5), "BYZANTINE MUSICAL SYMBOL FTHORA SKLIRON CHROMA VASIS", U_CHAR_NAME_ALIAS),
]

@pytest.mark.parametrize("char, expectedName, nameChoice", charNames)
def test_getCharNames(char: str, expectedName: str, nameChoice: int):
    assert CharNames.getCharName(ord(char), nameChoice) == expectedName

@pytest.mark.parametrize("expectedChar, name, nameChoice", charNames)
def test_charFromName(expectedChar: str, name: str, nameChoice: int):
    if nameChoice != U_EXTENDED_CHAR_NAME:  # can't lookup extended char names
            assert CharNames.charFromName(name, nameChoice) == ord(expectedChar)

